export const RoomActionTypes = {
  OPEN_ROOM: "OPEN_ROOM",
  SET_ROOM_DETAILS: "SET_ROOM_DETAILS",
  SET_ACTIVE_ROOMS: "SET_ACTIVE_ROOMS",
  SET_LOCAL_STREAM: "SET_LOCAL_STREAM",
  SET_REMOTE_STREAMS: "SET_REMOTE_STREAMS",
  SET_AUDIO_ONLY: "SET_AUDIO_ONLY",
  SET_SCREEN_SHARE_STREAM: "SET_SCREEN_SHARE_STREAM",
  SET_IS_USER_JOINED_WITH_ONLY_AUDIO: "SET_IS_USER_JOINED_WITH_ONLY_AUDIO",
};
